### PR TITLE
fixes #31 and #33

### LINKED ISSUE #31: found a small bug when there's a 0 in the thousands, millions, etc position
inside the `WHILE @Number > 0` loop, you might want to rework the following lines as indicated below, because it's not clearing the contents of the @vSubResult variable each time thru the loop. Therefore, when the `SELECT @vSubResult = Nam FROM @tDict WHERE Num = @v0Num` doesn't find a result, because @v0Num is 0, the @vSubResult variable retains its previous value.

Current Code:
			IF @v000Num = 0
			BEGIN
				SET @vSubResult = ''
			END
			ELSE 
			BEGIN

Proposed Code:
			SET @vSubResult = ''; --start out blank each time thru the loop to avoid remnants from previous iteration
			IF @v000Num > 0
			BEGIN 

When i made this change on my side, it works perfectly! 

Example of issue:
  Using Current Code:
    20200 -> 'twenty-two hundred   thousand two hundred'
  Using Proposed Code:
    20200 -> 'twenty- thousand two hundred'

(I have another "fix" suggestion for the dangling dash, shown above, which i also discovered while testing on this and other values, but i can submit that as a separate gh issue)

### PR DESCRIPTION
**Pull request by eseinbinder**

### CODE REVIEW

**Comment by eseinbinder** [comment]
well, i guess i only needed to create one PR for both commits, so there you have it. Enjoy!

**Comment by datnguye** [comment]
Hi @eseinbinder 
Thanks for managing to find the issues and created the PR. I will try review it this weekend and hopefully very straight forward to merge it!

**Comment by datnguye** [comment]
Hi @eseinbinder I have reviewed the PR. It is the very nice fix! I'm gonna approve and merge it to main.
New release will be updated soon.

Cheers!

**Comment by eseinbinder** [comment]
np, thanks..

**Pull request merged**
